// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package tc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTc returns the embedded CollectionSpec for tc.
func loadTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc: %w", err)
	}

	return spec, err
}

// loadTcObjects loads tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcObjects
//	*tcPrograms
//	*tcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcSpecs struct {
	tcProgramSpecs
	tcMapSpecs
	tcVariableSpecs
}

// tcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcProgramSpecs struct {
	TcEgressObserver *ebpf.ProgramSpec `ebpf:"tc_egress_observer"`
}

// tcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcMapSpecs struct {
	EgressPacketEvents *ebpf.MapSpec `ebpf:"egress_packet_events"`
}

// tcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcVariableSpecs struct {
	PACKET_DIRECTION_IN  *ebpf.VariableSpec `ebpf:"PACKET_DIRECTION_IN"`
	PACKET_DIRECTION_OUT *ebpf.VariableSpec `ebpf:"PACKET_DIRECTION_OUT"`
}

// tcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcObjects struct {
	tcPrograms
	tcMaps
	tcVariables
}

func (o *tcObjects) Close() error {
	return _TcClose(
		&o.tcPrograms,
		&o.tcMaps,
	)
}

// tcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcMaps struct {
	EgressPacketEvents *ebpf.Map `ebpf:"egress_packet_events"`
}

func (m *tcMaps) Close() error {
	return _TcClose(
		m.EgressPacketEvents,
	)
}

// tcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcVariables struct {
	PACKET_DIRECTION_IN  *ebpf.Variable `ebpf:"PACKET_DIRECTION_IN"`
	PACKET_DIRECTION_OUT *ebpf.Variable `ebpf:"PACKET_DIRECTION_OUT"`
}

// tcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcPrograms struct {
	TcEgressObserver *ebpf.Program `ebpf:"tc_egress_observer"`
}

func (p *tcPrograms) Close() error {
	return _TcClose(
		p.TcEgressObserver,
	)
}

func _TcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpfeb.o
var _TcBytes []byte
